#define SSD_SSID "Your WiFi SSID"
#define SSD_PSK "Your WiFi Password"
#define SSD_MQTT_SERVER "Your MQTT IP / Home Assistant IP"
#define SSD_MQTT_USER "Your MQTT username"
#define SSD_MQTT_PASS "Your MQTT password"
